service: order-service

provider:
  name: aws
  runtime: nodejs20.x
  region: us-east-1
  stage: dev

functions:
  getOrders:
    handler: handler.getOrders
    events:
      - http:
          path: orders
          method: get

  createOrder:
    handler: handler.createOrder
    events:
      - http:
          path: orders
          method: post
